openapi: 3.0.0
info:
    title: Simple User API
    description: A simple API to manage users.
    version: 1.0.0
servers:
    - url: https://api.example.com/v1
      description: Main production server
    - url: https://sandbox.api.example.com/v1
      description: Sandbox server for testing

paths:
    /users:
        get:
            summary: Get a list of users
            description: Retrieve a list of all users.
            responses:
                "200":
                    description: A list of users.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/User"
        post:
            summary: Create a new user
            description: Create a new user with the given information.
            requestBody:
                description: The user to create.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/NewUser"
            responses:
                "201":
                    description: The created user.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"

    /users/{userId}:
        get:
            summary: Get user by ID
            description: Retrieve a user by their ID.
            parameters:
                - name: userId
                  in: path
                  required: true
                  description: ID of the user to retrieve.
                  schema:
                      type: string
            responses:
                "200":
                    description: The user details.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/User"
                "404":
                    description: User not found.

components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: string
                    description: The unique identifier for the user.
                name:
                    type: string
                    description: The name of the user.
                email:
                    type: string
                    description: The email address of the user.
            required:
                - id
                - name
                - email

        NewUser:
            type: object
            properties:
                name:
                    type: string
                    description: The name of the user.
                email:
                    type: string
                    description: The email address of the user.
            required:
                - name
                - email
