name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.17.0"

            - name: Install frontend dependencies
              working-directory: frontend
              run: npm ci

            - name: Build frontend
              working-directory: frontend
              run: npm run build

    deploy:
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Start server on remote
              run: |
                  ssh user@your-server <<EOF
                    cd /projects/THOR/frontend
                    npm install
                    nohup npm start &
                  EOF
